server:
  port: 8080
  servlet:
    context-path: /
  http2:
    enabled: true
    use-forward-headers: true
  undertow:
    accesslog:
      dir: log/undertow/ # Undertow 日志存放目录
      # 是否启动日志
      enabled: true
      # 日志格式
      pattern: common
      # 日志文件名前缀
      prefix: access_log
      # 日志文件名后缀
      suffix: log
      # HTTP POST请求最大的大小
    max-http-post-size: 0
    # 以下的配置会影响buffer,这些 buffer 会用于服务器连接的 I O操作,有点类似 netty 的池化内存管理
    # 每块 buffer 的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置 IO 线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个 CPU 核心一个线程
      io: 2
      # 阻塞任务线程池, 当执行类似 servlet 请求阻塞操作, undertow 会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256